# Generated by Django 3.2.3 on 2022-02-09 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='percent',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_240',
            field=models.FileField(blank=True, null=True, upload_to='Videos/240p/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_360',
            field=models.FileField(blank=True, null=True, upload_to='Videos/360p/%Y/%m/%d'),
        ),
    ]
