# Generated by Django 3.2.3 on 2022-02-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220209_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='percent',
        ),
        migrations.AddField(
            model_name='video',
            name='time',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
