# Generated by Django 4.0.2 on 2022-02-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220209_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
